show databases;
use aids;
create table student(sid int,sname varchar(20),sdept varchar(20));
alter table student add sage int;
rename table std to student;
insert into student values(101,"ram","aids",20);
insert into student values(101,"raju","aiml",21);
insert into student values(103,"ravi","cse",20);
insert into student values(104,"meera","ece",21);
insert into student values(105,"reena","eee",19);
desc student;
update student set sid=102 where sname="raju";
select *from student;
drop table std;
select now();
drop table clg;
show tables;
insert into employee(eid,ename,age) values(101,"anil",50);
alter table student modify column sname varchar(25);
desc employee;
select *from employee;
update employee set age=20 where eid=105;
